build: off
shallow_clone: true

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
    matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        CMAKE_GENERATOR: NMake Makefiles
        BDIR: msvc2017_nmake
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        CMAKE_GENERATOR: Visual Studio 2017
        BDIR: msvc2017_vs2017

init:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")

build_script:
    - echo "%CMAKE_GENERATOR%"
    - mkdir build.%BDIR% && copy install.bat build.%BDIR%\ && cd build.%BDIR%
    - install.bat
    - cd %APPVEYOR_BUILD_FOLDER%

test_script:
    - if NOT exist "%PROGRAMFILES%"\zlib\lib\zlib.lib exit 1
    - if NOT exist "%PROGRAMFILES%"\zlib\bin\zlib.dll exit 1
    - if NOT exist "%PROGRAMFILES%"\zlib\include\zconf.h exit 1
    - if NOT exist "%PROGRAMFILES%"\zlib\include\zlib.h exit 1
