build: off
shallow_clone: true

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
    matrix:
      - image: "Visual Studio 2019"
        BDIR: msvc2019
        CMAKE_GENERATOR: NMake Makefiles

build_script:
    - echo "%CMAKE_GENERATOR%"
    - mkdir build.%BDIR% && copy install.bat build.%BDIR%\ && cd build.%BDIR%
    - install.bat
    - cd %APPVEYOR_BUILD_FOLDER%

test_script:
    - if NOT exist "%PROGRAMFILES%"\zlib\lib\zlib.lib exit 1
    - if NOT exist "%PROGRAMFILES%"\zlib\bin\zlib.dll exit 1
    - if NOT exist "%PROGRAMFILES%"\zlib\include\zconf.h exit 1
    - if NOT exist "%PROGRAMFILES%"\zlib\include\zlib.h exit 1
